### ISSUE TITLE
Typo in Chapter 3 Problem 2

### ISSUE THREAD

**Issue by Shuxiang-Hu** [jwdinius/prince-computer-vision#1]
Hi jwdinius

First of all, thank you very much for this repository. I found a typo in chapter 3 problem 2 where lambda was incorrectly typed as alpha. See the attached img.
![image](https://user-images.githubusercontent.com/56350867/184532103-ab7b8fa2-ead9-48cb-a89f-01c4441945ef.png)

Also, I got a different result from yours.
![image](https://user-images.githubusercontent.com/56350867/184532172-b8fa473c-f8eb-4e44-b806-3021a80352dd.png)

All best,

Hu Shuxiang

**Comment by jwdinius** [comment]
Thanks for filing the issue @Shuxiang-Hu!  I have reworked the problem and fixed the typos.
